    responses:
      '200':
        description: 'Success'
        body:
          text/xml:

      '400':
        description: 'Bad Request'
        body:
          text/xml:

      '401':
        description: 'Access Denied'
        body:
          text/xml:
      '404':
        description: 'Not found'
        body:
          text/xml:
      '406':
        description: 'Not Acceptable'
        body:
          text/xml:
      '422':
        description: 'Unprocessable Entity'
        body:
          text/xml:
      '500':
        description: 'Internal Server Error'
        body:
          text/plain:
      '501':
        description: 'Not Implemented'
        body:
          text/xml:
