    responses:
      '200':
        description: 'Success'
        body:
          text/xml:
            schema: OAI-PMH
      '400':
        description: 'Bad Request'
        body:
          text/xml:
            schema: OAI-PMH
      '401':
        description: 'Access Denied'
        body:
          text/xml:
            schema: OAI-PMH
      '404':
        description: 'Not found'
        body:
          text/xml:
            schema: OAI-PMH
      '422':
        description: 'Unprocessable Entity'
        body:
          text/xml:
            schema: OAI-PMH
      '500':
        description: 'Internal Server Error'
        body:
          text/plain:
      '501':
        description: 'Not Implemented'
        body:
          text/xml:
            schema: OAI-PMH
