    responses:
      '200':
        description: 'Success'
        body:
          text/xml:
            #schema: OAI-PMH

      '400':
        description: 'Bad Request'
        body:
          text/xml:
            #schema: OAI-PMH
            example:
              strict: false
              value: !include ../examples/bad_verb_error.sample

      '401':
        description: 'Access Denied'
        body:
          text/xml:
            #schema: OAI-PMH
            example:
              strict: false
              value: !include ../examples/resumption_token_error.sample
      '404':
        description: 'Not found'
        body:
          text/xml:
            #schema: OAI-PMH
            example:
              strict: false
              value: !include ../examples/no_records_error.sample
      '406':
        description: 'Not Acceptable'
        body:
          text/xml:
      '422':
        description: 'Unprocessable Entity'
        body:
          text/xml:
            #schema: OAI-PMH
            example:
              strict: false
              value: !include ../examples/no_metadata_format_error.sample
      '500':
        description: 'Internal Server Error'
        body:
          text/plain:
      '501':
        description: 'Not Implemented'
        body:
          text/xml:
            #schema: OAI-PMH
            example:
              strict: false
              value: !include ../examples/bad_verb_error.sample
